export default {
  "AFG": {
    "NAME_EN": "Afghanistan",
    "NAME_ZH": "阿富汗",
    "AREA_KM2": 652230,
    "POPULATION": 43844122,
    "GDP_USD_TRILLION": 0.02,
    "CAPITAL_EN": "Kabul",
    "CAPITAL_ZH": "喀布尔",
    "PINYIN_FULL": "afuhan",
    "PINYIN_INITIAL": "afh"
  },
  "AGO": {
    "NAME_EN": "Angola",
    "NAME_ZH": "安哥拉",
    "AREA_KM2": 1246700,
    "POPULATION": 39211854,
    "GDP_USD_TRILLION": 0.142,
    "CAPITAL_EN": "Luanda",
    "CAPITAL_ZH": "罗安达",
    "PINYIN_FULL": "angela",
    "PINYIN_INITIAL": "agl"
  },
  "ALB": {
    "NAME_EN": "Albania",
    "NAME_ZH": "阿尔巴尼亚",
    "AREA_KM2": 28748,
    "POPULATION": 2695189,
    "GDP_USD_TRILLION": 0.03,
    "CAPITAL_EN": "Tirana",
    "CAPITAL_ZH": "地拉那",
    "PINYIN_FULL": "aerbaniya",
    "PINYIN_INITIAL": "aebny"
  },
  "ARE": {
    "NAME_EN": "United Arab Emirates",
    "NAME_ZH": "阿联酋",
    "AREA_KM2": 83600,
    "POPULATION": 11380142,
    "GDP_USD_TRILLION": 0.572,
    "CAPITAL_EN": "Abu Dhabi",
    "CAPITAL_ZH": "阿布扎比",
    "PINYIN_FULL": "alianqiu",
    "PINYIN_INITIAL": "alq"
  },
  "ARG": {
    "NAME_EN": "Argentina",
    "NAME_ZH": "阿根廷",
    "AREA_KM2": 2780400,
    "POPULATION": 47473760,
    "GDP_USD_TRILLION": 0.681,
    "CAPITAL_EN": "Buenos Aires",
    "CAPITAL_ZH": "布宜诺斯艾利斯",
    "PINYIN_FULL": "agenting",
    "PINYIN_INITIAL": "agt"
  },
  "ARM": {
    "NAME_EN": "Armenia",
    "NAME_ZH": "亚美尼亚",
    "AREA_KM2": 29743,
    "POPULATION": 3071473,
    "GDP_USD_TRILLION": 0.029,
    "CAPITAL_EN": "Yerevan",
    "CAPITAL_ZH": "埃里温",
    "PINYIN_FULL": "yameiniya",
    "PINYIN_INITIAL": "ymny"
  },
  "ATA": {
    "NAME_EN": "Antarctica",
    "NAME_ZH": "南极洲",
    "AREA_KM2": 14000000,
    "POPULATION": 4490,
    "GDP_USD_TRILLION": 0.0009,
    "CAPITAL_EN": "N/A",
    "CAPITAL_ZH": "无",
    "PINYIN_FULL": "nanjizhou",
    "PINYIN_INITIAL": "njz"
  },
  "AUS": {
    "NAME_EN": "Australia",
    "NAME_ZH": "澳大利亚",
    "AREA_KM2": 7741220,
    "POPULATION": 27730356,
    "GDP_USD_TRILLION": 1.84,
    "CAPITAL_EN": "Canberra",
    "CAPITAL_ZH": "堪培拉",
    "PINYIN_FULL": "aodaliya",
    "PINYIN_INITIAL": "adly"
  },
  "AUT": {
    "NAME_EN": "Austria",
    "NAME_ZH": "奥地利",
    "AREA_KM2": 83879,
    "POPULATION": 9181697,
    "GDP_USD_TRILLION": 0.58,
    "CAPITAL_EN": "Vienna",
    "CAPITAL_ZH": "维也纳",
    "PINYIN_FULL": "aodili",
    "PINYIN_INITIAL": "adl"
  },
  "AZE": {
    "NAME_EN": "Azerbaijan",
    "NAME_ZH": "阿塞拜疆",
    "AREA_KM2": 86600,
    "POPULATION": 10371609,
    "GDP_USD_TRILLION": 0.076,
    "CAPITAL_EN": "Baku",
    "CAPITAL_ZH": "巴库",
    "PINYIN_FULL": "asaibaijiang",
    "PINYIN_INITIAL": "asbj"
  },
  "BDI": {
    "NAME_EN": "Burundi",
    "NAME_ZH": "布隆迪",
    "AREA_KM2": 27834,
    "POPULATION": 14469220,
    "GDP_USD_TRILLION": 0.0069,
    "CAPITAL_EN": "Gitega",
    "CAPITAL_ZH": "基特加",
    "PINYIN_FULL": "bulongdi",
    "PINYIN_INITIAL": "bld"
  },
  "BEL": {
    "NAME_EN": "Belgium",
    "NAME_ZH": "比利时",
    "AREA_KM2": 30528,
    "POPULATION": 11883495,
    "GDP_USD_TRILLION": 0.725,
    "CAPITAL_EN": "Brussels",
    "CAPITAL_ZH": "布鲁塞尔",
    "PINYIN_FULL": "bilishi",
    "PINYIN_INITIAL": "bls"
  },
  "BEN": {
    "NAME_EN": "Benin",
    "NAME_ZH": "贝宁",
    "AREA_KM2": 112622,
    "POPULATION": 14922529,
    "GDP_USD_TRILLION": 0.024,
    "CAPITAL_EN": "Porto-Novo",
    "CAPITAL_ZH": "波多诺伏",
    "PINYIN_FULL": "beining",
    "PINYIN_INITIAL": "bn"
  },
  "BFA": {
    "NAME_EN": "Burkina Faso",
    "NAME_ZH": "布基纳法索",
    "AREA_KM2": 274200,
    "POPULATION": 24095112,
    "GDP_USD_TRILLION": 0.027,
    "CAPITAL_EN": "Ouagadougou",
    "CAPITAL_ZH": "瓦加杜古",
    "PINYIN_FULL": "bujinafasuo",
    "PINYIN_INITIAL": "bjnfs"
  },
  "BGD": {
    "NAME_EN": "Bangladesh",
    "NAME_ZH": "孟加拉国",
    "AREA_KM2": 147570,
    "POPULATION": 173735877,
    "GDP_USD_TRILLION": 0.458,
    "CAPITAL_EN": "Dhaka",
    "CAPITAL_ZH": "达卡",
    "PINYIN_FULL": "mengjialaguo",
    "PINYIN_INITIAL": "mjlg"
  },
  "BGR": {
    "NAME_EN": "Bulgaria",
    "NAME_ZH": "保加利亚",
    "AREA_KM2": 110994,
    "POPULATION": 6262908,
    "GDP_USD_TRILLION": 0.131,
    "CAPITAL_EN": "Sofia",
    "CAPITAL_ZH": "索非亚",
    "PINYIN_FULL": "baojialiya",
    "PINYIN_INITIAL": "bjly"
  },
  "BHS": {
    "NAME_EN": "The Bahamas",
    "NAME_ZH": "巴哈马",
    "AREA_KM2": 13880,
    "POPULATION": 412637,
    "GDP_USD_TRILLION": 0.017,
    "CAPITAL_EN": "Nassau",
    "CAPITAL_ZH": "拿骚",
    "PINYIN_FULL": "bahama",
    "PINYIN_INITIAL": "bhm"
  },
  "BIH": {
    "NAME_EN": "Bosnia and Herz.",
    "NAME_ZH": "波黑",
    "AREA_KM2": 51209,
    "POPULATION": 3445144,
    "GDP_USD_TRILLION": 0.033,
    "CAPITAL_EN": "Sarajevo",
    "CAPITAL_ZH": "萨拉热窝",
    "PINYIN_FULL": "bohei",
    "PINYIN_INITIAL": "bh"
  },
  "BLR": {
    "NAME_EN": "Belarus",
    "NAME_ZH": "白俄罗斯",
    "AREA_KM2": 207600,
    "POPULATION": 9086966,
    "GDP_USD_TRILLION": 0.093,
    "CAPITAL_EN": "Minsk",
    "CAPITAL_ZH": "明斯克",
    "PINYIN_FULL": "baieluosi",
    "PINYIN_INITIAL": "bels"
  },
  "BLZ": {
    "NAME_EN": "Belize",
    "NAME_ZH": "伯利兹",
    "AREA_KM2": 22966,
    "POPULATION": 417494,
    "GDP_USD_TRILLION": 0.0033,
    "CAPITAL_EN": "Belmopan",
    "CAPITAL_ZH": "贝尔莫潘",
    "PINYIN_FULL": "bolizi",
    "PINYIN_INITIAL": "blz"
  },
  "BOL": {
    "NAME_EN": "Bolivia",
    "NAME_ZH": "玻利维亚",
    "AREA_KM2": 1098581,
    "POPULATION": 12581843,
    "GDP_USD_TRILLION": 0.064,
    "CAPITAL_EN": "Sucre",
    "CAPITAL_ZH": "苏克雷",
    "PINYIN_FULL": "boliweiya",
    "PINYIN_INITIAL": "blwy"
  },
  "BRA": {
    "NAME_EN": "Brazil",
    "NAME_ZH": "巴西",
    "AREA_KM2": 8515767,
    "POPULATION": 213361807,
    "GDP_USD_TRILLION": 2.28,
    "CAPITAL_EN": "Brasília",
    "CAPITAL_ZH": "巴西利亚",
    "PINYIN_FULL": "baxi",
    "PINYIN_INITIAL": "bx"
  },
  "BRN": {
    "NAME_EN": "Brunei",
    "NAME_ZH": "文莱",
    "AREA_KM2": 5765,
    "POPULATION": 459700,
    "GDP_USD_TRILLION": 0.016,
    "CAPITAL_EN": "Bandar Seri Begawan",
    "CAPITAL_ZH": "斯里巴加湾市",
    "PINYIN_FULL": "wenlai",
    "PINYIN_INITIAL": "wl"
  },
  "BTN": {
    "NAME_EN": "Bhutan",
    "NAME_ZH": "不丹",
    "AREA_KM2": 38394,
    "POPULATION": 790633,
    "GDP_USD_TRILLION": 0.0035,
    "CAPITAL_EN": "Thimphu",
    "CAPITAL_ZH": "廷布",
    "PINYIN_FULL": "budan",
    "PINYIN_INITIAL": "bd"
  },
  "BWA": {
    "NAME_EN": "Botswana",
    "NAME_ZH": "博茨瓦纳",
    "AREA_KM2": 581730,
    "POPULATION": 2549273,
    "GDP_USD_TRILLION": 0.02,
    "CAPITAL_EN": "Gaborone",
    "CAPITAL_ZH": "哈博罗内",
    "PINYIN_FULL": "bociwana",
    "PINYIN_INITIAL": "bcwn"
  },
  "CAF": {
    "NAME_EN": "Central African Rep.",
    "NAME_ZH": "中非",
    "AREA_KM2": 622984,
    "POPULATION": 5513282,
    "GDP_USD_TRILLION": 0.0032,
    "CAPITAL_EN": "Bangui",
    "CAPITAL_ZH": "班吉",
    "PINYIN_FULL": "zhongfei",
    "PINYIN_INITIAL": "zf"
  },
  "CAN": {
    "NAME_EN": "Canada",
    "NAME_ZH": "加拿大",
    "AREA_KM2": 9984670,
    "POPULATION": 41601578,
    "GDP_USD_TRILLION": 2.32,
    "CAPITAL_EN": "Ottawa",
    "CAPITAL_ZH": "渥太华",
    "PINYIN_FULL": "jianada",
    "PINYIN_INITIAL": "jnd"
  },
  "CHE": {
    "NAME_EN": "Switzerland",
    "NAME_ZH": "瑞士",
    "AREA_KM2": 41285,
    "POPULATION": 9025630,
    "GDP_USD_TRILLION": 1.04,
    "CAPITAL_EN": "Bern",
    "CAPITAL_ZH": "伯尔尼",
    "PINYIN_FULL": "ruishi",
    "PINYIN_INITIAL": "rs"
  },
  "CHL": {
    "NAME_EN": "Chile",
    "NAME_ZH": "智利",
    "AREA_KM2": 756102,
    "POPULATION": 20036669,
    "GDP_USD_TRILLION": 0.355,
    "CAPITAL_EN": "Santiago",
    "CAPITAL_ZH": "圣地亚哥",
    "PINYIN_FULL": "zhili",
    "PINYIN_INITIAL": "zl"
  },
  "CHN": {
    "NAME_EN": "China",
    "NAME_ZH": "中国",
    "AREA_KM2": 9596961,
    "POPULATION": 1405079906,
    "GDP_USD_TRILLION": 19.63,
    "CAPITAL_EN": "Beijing",
    "CAPITAL_ZH": "北京",
    "PINYIN_FULL": "zhongguo",
    "PINYIN_INITIAL": "zg"
  },
  "CIV": {
    "NAME_EN": "Côte d'Ivoire",
    "NAME_ZH": "科特迪瓦",
    "AREA_KM2": 322463,
    "POPULATION": 32897447,
    "GDP_USD_TRILLION": 0.099,
    "CAPITAL_EN": "Yamoussoukro",
    "CAPITAL_ZH": "亚穆苏克罗",
    "PINYIN_FULL": "ketediwa",
    "PINYIN_INITIAL": "ktdw"
  },
  "CMR": {
    "NAME_EN": "Cameroon",
    "NAME_ZH": "喀麦隆",
    "AREA_KM2": 475442,
    "POPULATION": 29879337,
    "GDP_USD_TRILLION": 0.059,
    "CAPITAL_EN": "Yaoundé",
    "CAPITAL_ZH": "雅温得",
    "PINYIN_FULL": "kamailong",
    "PINYIN_INITIAL": "kml"
  },
  "COD": {
    "NAME_EN": "Dem. Rep. Congo",
    "NAME_ZH": "刚果(金)",
    "AREA_KM2": 2344858,
    "POPULATION": 106552267,
    "GDP_USD_TRILLION": 0.093,
    "CAPITAL_EN": "Kinshasa",
    "CAPITAL_ZH": "金沙萨",
    "PINYIN_FULL": "gangguo(jin)",
    "PINYIN_INITIAL": "gg(j)"
  },
  "COG": {
    "NAME_EN": "Congo",
    "NAME_ZH": "刚果(布)",
    "AREA_KM2": 342000,
    "POPULATION": 6486113,
    "GDP_USD_TRILLION": 0.016,
    "CAPITAL_EN": "Brazzaville",
    "CAPITAL_ZH": "布拉柴维尔",
    "PINYIN_FULL": "gangguo(bu)",
    "PINYIN_INITIAL": "gg(b)"
  },
  "COL": {
    "NAME_EN": "Colombia",
    "NAME_ZH": "哥伦比亚",
    "AREA_KM2": 1141748,
    "POPULATION": 53048000,
    "GDP_USD_TRILLION": 0.457,
    "CAPITAL_EN": "Bogotá",
    "CAPITAL_ZH": "波哥大",
    "PINYIN_FULL": "gelunbiya",
    "PINYIN_INITIAL": "glby"
  },
  "CRI": {
    "NAME_EN": "Costa Rica",
    "NAME_ZH": "哥斯达黎加",
    "AREA_KM2": 51100,
    "POPULATION": 5370133,
    "GDP_USD_TRILLION": 0.103,
    "CAPITAL_EN": "San José",
    "CAPITAL_ZH": "圣何塞",
    "PINYIN_FULL": "gesidalijia",
    "PINYIN_INITIAL": "gsdlj"
  },
  "CUB": {
    "NAME_EN": "Cuba",
    "NAME_ZH": "古巴",
    "AREA_KM2": 109884,
    "POPULATION": 10979783,
    "GDP_USD_TRILLION": 0.107,
    "CAPITAL_EN": "Havana",
    "CAPITAL_ZH": "哈瓦那",
    "PINYIN_FULL": "guba",
    "PINYIN_INITIAL": "gb"
  },
  "CYP": {
    "NAME_EN": "Cyprus",
    "NAME_ZH": "塞浦路斯",
    "AREA_KM2": 9251,
    "POPULATION": 982966,
    "GDP_USD_TRILLION": 0.041,
    "CAPITAL_EN": "Nicosia",
    "CAPITAL_ZH": "尼科西亚",
    "PINYIN_FULL": "saipulusi",
    "PINYIN_INITIAL": "spls"
  },
  "CZE": {
    "NAME_EN": "Czechia",
    "NAME_ZH": "捷克",
    "AREA_KM2": 78867,
    "POPULATION": 10903521,
    "GDP_USD_TRILLION": 0.389,
    "CAPITAL_EN": "Prague",
    "CAPITAL_ZH": "布拉格",
    "PINYIN_FULL": "jieke",
    "PINYIN_INITIAL": "jk"
  },
  "DEU": {
    "NAME_EN": "Germany",
    "NAME_ZH": "德国",
    "AREA_KM2": 357022,
    "POPULATION": 83523500,
    "GDP_USD_TRILLION": 5.05,
    "CAPITAL_EN": "Berlin",
    "CAPITAL_ZH": "柏林",
    "PINYIN_FULL": "deguo",
    "PINYIN_INITIAL": "dg"
  },
  "DJI": {
    "NAME_EN": "Djibouti",
    "NAME_ZH": "吉布提",
    "AREA_KM2": 23200,
    "POPULATION": 1056058,
    "GDP_USD_TRILLION": 0.0044,
    "CAPITAL_EN": "Djibouti",
    "CAPITAL_ZH": "吉布提",
    "PINYIN_FULL": "jibuti",
    "PINYIN_INITIAL": "jbt"
  },
  "DNK": {
    "NAME_EN": "Denmark",
    "NAME_ZH": "丹麦",
    "AREA_KM2": 43094,
    "POPULATION": 5992734,
    "GDP_USD_TRILLION": 0.462,
    "CAPITAL_EN": "Copenhagen",
    "CAPITAL_ZH": "哥本哈根",
    "PINYIN_FULL": "danmai",
    "PINYIN_INITIAL": "dm"
  },
  "DOM": {
    "NAME_EN": "Dominican Rep.",
    "NAME_ZH": "多米尼加",
    "AREA_KM2": 48671,
    "POPULATION": 10885422,
    "GDP_USD_TRILLION": 0.128,
    "CAPITAL_EN": "Santo Domingo",
    "CAPITAL_ZH": "圣多明各",
    "PINYIN_FULL": "duominijia",
    "PINYIN_INITIAL": "dmnj"
  },
  "DZA": {
    "NAME_EN": "Algeria",
    "NAME_ZH": "阿尔及利亚",
    "AREA_KM2": 2381741,
    "POPULATION": 47251466,
    "GDP_USD_TRILLION": 0.286,
    "CAPITAL_EN": "Algiers",
    "CAPITAL_ZH": "阿尔及尔",
    "PINYIN_FULL": "aerjiliya",
    "PINYIN_INITIAL": "aejly"
  },
  "ECU": {
    "NAME_EN": "Ecuador",
    "NAME_ZH": "厄瓜多尔",
    "AREA_KM2": 283561,
    "POPULATION": 18103660,
    "GDP_USD_TRILLION": 0.13,
    "CAPITAL_EN": "Quito",
    "CAPITAL_ZH": "基多",
    "PINYIN_FULL": "eguaduoer",
    "PINYIN_INITIAL": "egde"
  },
  "EGY": {
    "NAME_EN": "Egypt",
    "NAME_ZH": "埃及",
    "AREA_KM2": 1002450,
    "POPULATION": 107900000,
    "GDP_USD_TRILLION": 0.365,
    "CAPITAL_EN": "Cairo",
    "CAPITAL_ZH": "开罗",
    "PINYIN_FULL": "aiji",
    "PINYIN_INITIAL": "aj"
  },
  "ERI": {
    "NAME_EN": "Eritrea",
    "NAME_ZH": "厄立特里亚",
    "AREA_KM2": 117600,
    "POPULATION": 3535603,
    "GDP_USD_TRILLION": 0.0021,
    "CAPITAL_EN": "Asmara",
    "CAPITAL_ZH": "阿斯马拉",
    "PINYIN_FULL": "eliteliya",
    "PINYIN_INITIAL": "eltly"
  },
  "ESH": {
    "NAME_EN": "Western Sahara",
    "NAME_ZH": "西撒哈拉",
    "AREA_KM2": 266000,
    "POPULATION": 603253,
    "GDP_USD_TRILLION": 0.0009,
    "CAPITAL_EN": "El Aaiún",
    "CAPITAL_ZH": "阿尤恩",
    "PINYIN_FULL": "xisahala",
    "PINYIN_INITIAL": "xshl"
  },
  "ESP": {
    "NAME_EN": "Spain",
    "NAME_ZH": "西班牙",
    "AREA_KM2": 505992,
    "POPULATION": 49720741,
    "GDP_USD_TRILLION": 1.9,
    "CAPITAL_EN": "Madrid",
    "CAPITAL_ZH": "马德里",
    "PINYIN_FULL": "xibanya",
    "PINYIN_INITIAL": "xby"
  },
  "EST": {
    "NAME_EN": "Estonia",
    "NAME_ZH": "爱沙尼亚",
    "AREA_KM2": 45227,
    "POPULATION": 1369373,
    "GDP_USD_TRILLION": 0.047,
    "CAPITAL_EN": "Tallinn",
    "CAPITAL_ZH": "塔林",
    "PINYIN_FULL": "aishaniya",
    "PINYIN_INITIAL": "asny"
  },
  "ETH": {
    "NAME_EN": "Ethiopia",
    "NAME_ZH": "埃塞俄比亚",
    "AREA_KM2": 1104300,
    "POPULATION": 110600000,
    "GDP_USD_TRILLION": 0.109,
    "CAPITAL_EN": "Addis Ababa",
    "CAPITAL_ZH": "亚的斯亚贝巴",
    "PINYIN_FULL": "aisaiebiya",
    "PINYIN_INITIAL": "aseby"
  },
  "FIN": {
    "NAME_EN": "Finland",
    "NAME_ZH": "芬兰",
    "AREA_KM2": 338424,
    "POPULATION": 5611675,
    "GDP_USD_TRILLION": 0.317,
    "CAPITAL_EN": "Helsinki",
    "CAPITAL_ZH": "赫尔辛基",
    "PINYIN_FULL": "fenlan",
    "PINYIN_INITIAL": "fl"
  },
  "FJI": {
    "NAME_EN": "Fiji",
    "NAME_ZH": "斐济",
    "AREA_KM2": 18272,
    "POPULATION": 928264,
    "GDP_USD_TRILLION": 0.006,
    "CAPITAL_EN": "Suva",
    "CAPITAL_ZH": "苏瓦",
    "PINYIN_FULL": "feiji",
    "PINYIN_INITIAL": "fj"
  },
  "FLK": {
    "NAME_EN": "Falkland Islands",
    "NAME_ZH": "福克兰群岛",
    "AREA_KM2": 12173,
    "POPULATION": 3398,
    "GDP_USD_TRILLION": 0.0003,
    "CAPITAL_EN": "Stanley",
    "CAPITAL_ZH": "斯坦利",
    "PINYIN_FULL": "fukelanqundao",
    "PINYIN_INITIAL": "fklqd"
  },
  "FRA": {
    "NAME_EN": "France",
    "NAME_ZH": "法国",
    "AREA_KM2": 551695,
    "POPULATION": 68851996,
    "GDP_USD_TRILLION": 3.37,
    "CAPITAL_EN": "Paris",
    "CAPITAL_ZH": "巴黎",
    "PINYIN_FULL": "faguo",
    "PINYIN_INITIAL": "fg"
  },
  "GAB": {
    "NAME_EN": "Gabon",
    "NAME_ZH": "加蓬",
    "AREA_KM2": 267667,
    "POPULATION": 2306261,
    "GDP_USD_TRILLION": 0.022,
    "CAPITAL_EN": "Libreville",
    "CAPITAL_ZH": "利伯维尔",
    "PINYIN_FULL": "jiapeng",
    "PINYIN_INITIAL": "jp"
  },
  "GBR": {
    "NAME_EN": "United Kingdom",
    "NAME_ZH": "英国",
    "AREA_KM2": 243610,
    "POPULATION": 69487000,
    "GDP_USD_TRILLION": 4,
    "CAPITAL_EN": "London",
    "CAPITAL_ZH": "伦敦",
    "PINYIN_FULL": "yingguo",
    "PINYIN_INITIAL": "yg"
  },
  "GEO": {
    "NAME_EN": "Georgia",
    "NAME_ZH": "格鲁吉亚",
    "AREA_KM2": 69700,
    "POPULATION": 3693803,
    "GDP_USD_TRILLION": 0.038,
    "CAPITAL_EN": "Tbilisi",
    "CAPITAL_ZH": "第比利斯",
    "PINYIN_FULL": "gelujiya",
    "PINYIN_INITIAL": "gljy"
  },
  "GHA": {
    "NAME_EN": "Ghana",
    "NAME_ZH": "加纳",
    "AREA_KM2": 238533,
    "POPULATION": 35064273,
    "GDP_USD_TRILLION": 0.115,
    "CAPITAL_EN": "Accra",
    "CAPITAL_ZH": "阿克拉",
    "PINYIN_FULL": "jiana",
    "PINYIN_INITIAL": "jn"
  },
  "GIN": {
    "NAME_EN": "Guinea",
    "NAME_ZH": "几内亚",
    "AREA_KM2": 245857,
    "POPULATION": 15802772,
    "GDP_USD_TRILLION": 0.027,
    "CAPITAL_EN": "Conakry",
    "CAPITAL_ZH": "科纳克里",
    "PINYIN_FULL": "jineiya",
    "PINYIN_INITIAL": "jny"
  },
  "GMB": {
    "NAME_EN": "Gambia",
    "NAME_ZH": "冈比亚",
    "AREA_KM2": 11300,
    "POPULATION": 2857680,
    "GDP_USD_TRILLION": 0.0026,
    "CAPITAL_EN": "Banjul",
    "CAPITAL_ZH": "班珠尔",
    "PINYIN_FULL": "gangbiya",
    "PINYIN_INITIAL": "gby"
  },
  "GNB": {
    "NAME_EN": "Guinea-Bissau",
    "NAME_ZH": "几内亚比绍",
    "AREA_KM2": 36125,
    "POPULATION": 2019242,
    "GDP_USD_TRILLION": 0.0026,
    "CAPITAL_EN": "Bissau",
    "CAPITAL_ZH": "比绍",
    "PINYIN_FULL": "jineiyabishao",
    "PINYIN_INITIAL": "jnybs"
  },
  "GNQ": {
    "NAME_EN": "Eq. Guinea",
    "NAME_ZH": "赤道几内亚",
    "AREA_KM2": 28051,
    "POPULATION": 1636622,
    "GDP_USD_TRILLION": 0.012,
    "CAPITAL_EN": "Malabo",
    "CAPITAL_ZH": "马拉博",
    "PINYIN_FULL": "chidaojineiya",
    "PINYIN_INITIAL": "cdjny"
  },
  "GRC": {
    "NAME_EN": "Greece",
    "NAME_ZH": "希腊",
    "AREA_KM2": 131957,
    "POPULATION": 10372335,
    "GDP_USD_TRILLION": 0.28,
    "CAPITAL_EN": "Athens",
    "CAPITAL_ZH": "雅典",
    "PINYIN_FULL": "xila",
    "PINYIN_INITIAL": "xl"
  },
  "GRL": {
    "NAME_EN": "Greenland",
    "NAME_ZH": "格陵兰",
    "AREA_KM2": 2166086,
    "POPULATION": 56836,
    "GDP_USD_TRILLION": 0.0033,
    "CAPITAL_EN": "Nuuk",
    "CAPITAL_ZH": "努克",
    "PINYIN_FULL": "gelinglan",
    "PINYIN_INITIAL": "gll"
  },
  "GTM": {
    "NAME_EN": "Guatemala",
    "NAME_ZH": "危地马拉",
    "AREA_KM2": 108889,
    "POPULATION": 18664048,
    "GDP_USD_TRILLION": 0.121,
    "CAPITAL_EN": "Guatemala City",
    "CAPITAL_ZH": "危地马拉城",
    "PINYIN_FULL": "weidimala",
    "PINYIN_INITIAL": "wdml"
  },
  "GUY": {
    "NAME_EN": "Guyana",
    "NAME_ZH": "圭亚那",
    "AREA_KM2": 214969,
    "POPULATION": 1003846,
    "GDP_USD_TRILLION": 0.027,
    "CAPITAL_EN": "Georgetown",
    "CAPITAL_ZH": "乔治敦",
    "PINYIN_FULL": "guiyana",
    "PINYIN_INITIAL": "gyn"
  },
  "HND": {
    "NAME_EN": "Honduras",
    "NAME_ZH": "洪都拉斯",
    "AREA_KM2": 112492,
    "POPULATION": 11005850,
    "GDP_USD_TRILLION": 0.04,
    "CAPITAL_EN": "Tegucigalpa",
    "CAPITAL_ZH": "特古西加尔巴",
    "PINYIN_FULL": "hongdoulasi",
    "PINYIN_INITIAL": "hdls"
  },
  "HRV": {
    "NAME_EN": "Croatia",
    "NAME_ZH": "克罗地亚",
    "AREA_KM2": 56594,
    "POPULATION": 3873942,
    "GDP_USD_TRILLION": 0.106,
    "CAPITAL_EN": "Zagreb",
    "CAPITAL_ZH": "萨格勒布",
    "PINYIN_FULL": "keluodiya",
    "PINYIN_INITIAL": "kldy"
  },
  "HTI": {
    "NAME_EN": "Haiti",
    "NAME_ZH": "海地",
    "AREA_KM2": 27750,
    "POPULATION": 12556995,
    "GDP_USD_TRILLION": 0.032,
    "CAPITAL_EN": "Port-au-Prince",
    "CAPITAL_ZH": "太子港",
    "PINYIN_FULL": "haidi",
    "PINYIN_INITIAL": "hd"
  },
  "HUN": {
    "NAME_EN": "Hungary",
    "NAME_ZH": "匈牙利",
    "AREA_KM2": 93028,
    "POPULATION": 9559958,
    "GDP_USD_TRILLION": 0.247,
    "CAPITAL_EN": "Budapest",
    "CAPITAL_ZH": "布达佩斯",
    "PINYIN_FULL": "xiongyali",
    "PINYIN_INITIAL": "xyl"
  },
  "IDN": {
    "NAME_EN": "Indonesia",
    "NAME_ZH": "印度尼西亚",
    "AREA_KM2": 1904569,
    "POPULATION": 284438780,
    "GDP_USD_TRILLION": 1.45,
    "CAPITAL_EN": "Jakarta",
    "CAPITAL_ZH": "雅加达",
    "PINYIN_FULL": "yindunixiya",
    "PINYIN_INITIAL": "ydnxy"
  },
  "IND": {
    "NAME_EN": "India",
    "NAME_ZH": "印度",
    "AREA_KM2": 3287263,
    "POPULATION": 1463865525,
    "GDP_USD_TRILLION": 3.92,
    "CAPITAL_EN": "New Delhi",
    "CAPITAL_ZH": "新德里",
    "PINYIN_FULL": "yindu",
    "PINYIN_INITIAL": "yd"
  },
  "IRL": {
    "NAME_EN": "Ireland",
    "NAME_ZH": "爱尔兰",
    "AREA_KM2": 70273,
    "POPULATION": 5496570,
    "GDP_USD_TRILLION": 0.718,
    "CAPITAL_EN": "Dublin",
    "CAPITAL_ZH": "都柏林",
    "PINYIN_FULL": "aierlan",
    "PINYIN_INITIAL": "ael"
  },
  "IRN": {
    "NAME_EN": "Iran",
    "NAME_ZH": "伊朗",
    "AREA_KM2": 1648195,
    "POPULATION": 87057188,
    "GDP_USD_TRILLION": 0.371,
    "CAPITAL_EN": "Tehran",
    "CAPITAL_ZH": "德黑兰",
    "PINYIN_FULL": "yilang",
    "PINYIN_INITIAL": "yl"
  },
  "IRQ": {
    "NAME_EN": "Iraq",
    "NAME_ZH": "伊拉克",
    "AREA_KM2": 438317,
    "POPULATION": 45520500,
    "GDP_USD_TRILLION": 0.264,
    "CAPITAL_EN": "Baghdad",
    "CAPITAL_ZH": "巴格达",
    "PINYIN_FULL": "yilake",
    "PINYIN_INITIAL": "ylk"
  },
  "ISL": {
    "NAME_EN": "Iceland",
    "NAME_ZH": "冰岛",
    "AREA_KM2": 103000,
    "POPULATION": 389444,
    "GDP_USD_TRILLION": 0.039,
    "CAPITAL_EN": "Reykjavik",
    "CAPITAL_ZH": "雷克雅未克",
    "PINYIN_FULL": "bingdao",
    "PINYIN_INITIAL": "bd"
  },
  "ISR": {
    "NAME_EN": "Israel",
    "NAME_ZH": "以色列",
    "AREA_KM2": 20770,
    "POPULATION": 10123142,
    "GDP_USD_TRILLION": 0.611,
    "CAPITAL_EN": "Jerusalem",
    "CAPITAL_ZH": "耶路撒冷",
    "PINYIN_FULL": "yiselie",
    "PINYIN_INITIAL": "ysl"
  },
  "ITA": {
    "NAME_EN": "Italy",
    "NAME_ZH": "意大利",
    "AREA_KM2": 301340,
    "POPULATION": 58934357,
    "GDP_USD_TRILLION": 2.55,
    "CAPITAL_EN": "Rome",
    "CAPITAL_ZH": "罗马",
    "PINYIN_FULL": "yidali",
    "PINYIN_INITIAL": "ydl"
  },
  "JAM": {
    "NAME_EN": "Jamaica",
    "NAME_ZH": "牙买加",
    "AREA_KM2": 10991,
    "POPULATION": 2752827,
    "GDP_USD_TRILLION": 0.022,
    "CAPITAL_EN": "Kingston",
    "CAPITAL_ZH": "金斯敦",
    "PINYIN_FULL": "yamaijia",
    "PINYIN_INITIAL": "ymj"
  },
  "JOR": {
    "NAME_EN": "Jordan",
    "NAME_ZH": "约旦",
    "AREA_KM2": 89342,
    "POPULATION": 11520685,
    "GDP_USD_TRILLION": 0.062,
    "CAPITAL_EN": "Amman",
    "CAPITAL_ZH": "安曼",
    "PINYIN_FULL": "yuedan",
    "PINYIN_INITIAL": "yd"
  },
  "JPN": {
    "NAME_EN": "Japan",
    "NAME_ZH": "日本",
    "AREA_KM2": 377975,
    "POPULATION": 123290921,
    "GDP_USD_TRILLION": 4.44,
    "CAPITAL_EN": "Tokyo",
    "CAPITAL_ZH": "东京",
    "PINYIN_FULL": "riben",
    "PINYIN_INITIAL": "rb"
  },
  "KAZ": {
    "NAME_EN": "Kazakhstan",
    "NAME_ZH": "哈萨克斯坦",
    "AREA_KM2": 2724900,
    "POPULATION": 20380366,
    "GDP_USD_TRILLION": 0.303,
    "CAPITAL_EN": "Nur-Sultan",
    "CAPITAL_ZH": "努尔苏丹",
    "PINYIN_FULL": "hasakesitan",
    "PINYIN_INITIAL": "hskst"
  },
  "KEN": {
    "NAME_EN": "Kenya",
    "NAME_ZH": "肯尼亚",
    "AREA_KM2": 580367,
    "POPULATION": 53353847,
    "GDP_USD_TRILLION": 0.136,
    "CAPITAL_EN": "Nairobi",
    "CAPITAL_ZH": "内罗毕",
    "PINYIN_FULL": "kenniya",
    "PINYIN_INITIAL": "kny"
  },
  "KGZ": {
    "NAME_EN": "Kyrgyzstan",
    "NAME_ZH": "吉尔吉斯斯坦",
    "AREA_KM2": 199951,
    "POPULATION": 7226824,
    "GDP_USD_TRILLION": 0.022,
    "CAPITAL_EN": "Bishkek",
    "CAPITAL_ZH": "比什凯克",
    "PINYIN_FULL": "jierjisisitan",
    "PINYIN_INITIAL": "jejsst"
  },
  "KHM": {
    "NAME_EN": "Cambodia",
    "NAME_ZH": "柬埔寨",
    "AREA_KM2": 181035,
    "POPULATION": 17847982,
    "GDP_USD_TRILLION": 0.049,
    "CAPITAL_EN": "Phnom Penh",
    "CAPITAL_ZH": "金边",
    "PINYIN_FULL": "jianpuzhai",
    "PINYIN_INITIAL": "jpz"
  },
  "KOR": {
    "NAME_EN": "South Korea",
    "NAME_ZH": "韩国",
    "AREA_KM2": 100210,
    "POPULATION": 51684564,
    "GDP_USD_TRILLION": 1.87,
    "CAPITAL_EN": "Seoul",
    "CAPITAL_ZH": "首尔",
    "PINYIN_FULL": "hanguo",
    "PINYIN_INITIAL": "hg"
  },
  "KWT": {
    "NAME_EN": "Kuwait",
    "NAME_ZH": "科威特",
    "AREA_KM2": 17818,
    "POPULATION": 5111767,
    "GDP_USD_TRILLION": 0.158,
    "CAPITAL_EN": "Kuwait City",
    "CAPITAL_ZH": "科威特城",
    "PINYIN_FULL": "keweite",
    "PINYIN_INITIAL": "kwt"
  },
  "LAO": {
    "NAME_EN": "Laos",
    "NAME_ZH": "老挝",
    "AREA_KM2": 236800,
    "POPULATION": 7787785,
    "GDP_USD_TRILLION": 0.018,
    "CAPITAL_EN": "Vientiane",
    "CAPITAL_ZH": "万象",
    "PINYIN_FULL": "laowo",
    "PINYIN_INITIAL": "lw"
  },
  "LBN": {
    "NAME_EN": "Lebanon",
    "NAME_ZH": "黎巴嫩",
    "AREA_KM2": 10452,
    "POPULATION": 5353930,
    "GDP_USD_TRILLION": 0.034,
    "CAPITAL_EN": "Beirut",
    "CAPITAL_ZH": "贝鲁特",
    "PINYIN_FULL": "libanen",
    "PINYIN_INITIAL": "lbn"
  },
  "LBR": {
    "NAME_EN": "Liberia",
    "NAME_ZH": "利比里亚",
    "AREA_KM2": 111369,
    "POPULATION": 5731206,
    "GDP_USD_TRILLION": 0.0052,
    "CAPITAL_EN": "Monrovia",
    "CAPITAL_ZH": "蒙罗维亚",
    "PINYIN_FULL": "libiliya",
    "PINYIN_INITIAL": "lbly"
  },
  "LBY": {
    "NAME_EN": "Libya",
    "NAME_ZH": "利比亚",
    "AREA_KM2": 1759540,
    "POPULATION": 7457164,
    "GDP_USD_TRILLION": 0.045,
    "CAPITAL_EN": "Tripoli",
    "CAPITAL_ZH": "的黎波里",
    "PINYIN_FULL": "libiya",
    "PINYIN_INITIAL": "lby"
  },
  "LKA": {
    "NAME_EN": "Sri Lanka",
    "NAME_ZH": "斯里兰卡",
    "AREA_KM2": 65610,
    "POPULATION": 21916000,
    "GDP_USD_TRILLION": 0.099,
    "CAPITAL_EN": "Colombo",
    "CAPITAL_ZH": "科伦坡",
    "PINYIN_FULL": "sililanka",
    "PINYIN_INITIAL": "sllk"
  },
  "LSO": {
    "NAME_EN": "Lesotho",
    "NAME_ZH": "莱索托",
    "AREA_KM2": 30355,
    "POPULATION": 2365740,
    "GDP_USD_TRILLION": 0.0029,
    "CAPITAL_EN": "Maseru",
    "CAPITAL_ZH": "马塞卢",
    "PINYIN_FULL": "laisuotuo",
    "PINYIN_INITIAL": "lst"
  },
  "LTU": {
    "NAME_EN": "Lithuania",
    "NAME_ZH": "立陶宛",
    "AREA_KM2": 65300,
    "POPULATION": 2890664,
    "GDP_USD_TRILLION": 0.095,
    "CAPITAL_EN": "Vilnius",
    "CAPITAL_ZH": "维尔纽斯",
    "PINYIN_FULL": "litaowan",
    "PINYIN_INITIAL": "ltw"
  },
  "LUX": {
    "NAME_EN": "Luxembourg",
    "NAME_ZH": "卢森堡",
    "AREA_KM2": 2586,
    "POPULATION": 681973,
    "GDP_USD_TRILLION": 0.101,
    "CAPITAL_EN": "Luxembourg",
    "CAPITAL_ZH": "卢森堡",
    "PINYIN_FULL": "lusenbao",
    "PINYIN_INITIAL": "lsb"
  },
  "LVA": {
    "NAME_EN": "Latvia",
    "NAME_ZH": "拉脱维亚",
    "AREA_KM2": 64559,
    "POPULATION": 1860565,
    "GDP_USD_TRILLION": 0.049,
    "CAPITAL_EN": "Riga",
    "CAPITAL_ZH": "里加",
    "PINYIN_FULL": "latuoweiya",
    "PINYIN_INITIAL": "ltwy"
  },
  "MAR": {
    "NAME_EN": "Morocco",
    "NAME_ZH": "摩洛哥",
    "AREA_KM2": 446550,
    "POPULATION": 37712000,
    "GDP_USD_TRILLION": 0.183,
    "CAPITAL_EN": "Rabat",
    "CAPITAL_ZH": "拉巴特",
    "PINYIN_FULL": "moluoge",
    "PINYIN_INITIAL": "mlg"
  },
  "MDA": {
    "NAME_EN": "Moldova",
    "NAME_ZH": "摩尔多瓦",
    "AREA_KM2": 33846,
    "POPULATION": 2381300,
    "GDP_USD_TRILLION": 0.02,
    "CAPITAL_EN": "Chișinău",
    "CAPITAL_ZH": "基希讷乌",
    "PINYIN_FULL": "moerduowa",
    "PINYIN_INITIAL": "medw"
  },
  "MDG": {
    "NAME_EN": "Madagascar",
    "NAME_ZH": "马达加斯加",
    "AREA_KM2": 587041,
    "POPULATION": 31444495,
    "GDP_USD_TRILLION": 0.02,
    "CAPITAL_EN": "Antananarivo",
    "CAPITAL_ZH": "塔那那利佛",
    "PINYIN_FULL": "madajiasijia",
    "PINYIN_INITIAL": "mdjsj"
  },
  "MEX": {
    "NAME_EN": "Mexico",
    "NAME_ZH": "墨西哥",
    "AREA_KM2": 1964375,
    "POPULATION": 133367428,
    "GDP_USD_TRILLION": 1.83,
    "CAPITAL_EN": "Mexico City",
    "CAPITAL_ZH": "墨西哥城",
    "PINYIN_FULL": "moxige",
    "PINYIN_INITIAL": "mxg"
  },
  "MKD": {
    "NAME_EN": "North Macedonia",
    "NAME_ZH": "北马其顿",
    "AREA_KM2": 25713,
    "POPULATION": 1815146,
    "GDP_USD_TRILLION": 0.019,
    "CAPITAL_EN": "Skopje",
    "CAPITAL_ZH": "斯科普里",
    "PINYIN_FULL": "beimaqidun",
    "PINYIN_INITIAL": "bmqd"
  },
  "MLI": {
    "NAME_EN": "Mali",
    "NAME_ZH": "马里",
    "AREA_KM2": 1240192,
    "POPULATION": 25246838,
    "GDP_USD_TRILLION": 0.03,
    "CAPITAL_EN": "Bamako",
    "CAPITAL_ZH": "巴马科",
    "PINYIN_FULL": "mali",
    "PINYIN_INITIAL": "ml"
  },
  "MMR": {
    "NAME_EN": "Myanmar",
    "NAME_ZH": "缅甸",
    "AREA_KM2": 676578,
    "POPULATION": 54850648,
    "GDP_USD_TRILLION": 0.082,
    "CAPITAL_EN": "Naypyidaw",
    "CAPITAL_ZH": "内比都",
    "PINYIN_FULL": "miandian",
    "PINYIN_INITIAL": "md"
  },
  "MNE": {
    "NAME_EN": "Montenegro",
    "NAME_ZH": "黑山",
    "AREA_KM2": 13812,
    "POPULATION": 624153,
    "GDP_USD_TRILLION": 0.0092,
    "CAPITAL_EN": "Podgorica",
    "CAPITAL_ZH": "波德戈里察",
    "PINYIN_FULL": "heishan",
    "PINYIN_INITIAL": "hs"
  },
  "MNG": {
    "NAME_EN": "Mongolia",
    "NAME_ZH": "蒙古",
    "AREA_KM2": 1564110,
    "POPULATION": 3583615,
    "GDP_USD_TRILLION": 0.025,
    "CAPITAL_EN": "Ulaanbaatar",
    "CAPITAL_ZH": "乌兰巴托",
    "PINYIN_FULL": "menggu",
    "PINYIN_INITIAL": "mg"
  },
  "MOZ": {
    "NAME_EN": "Mozambique",
    "NAME_ZH": "莫桑比克",
    "AREA_KM2": 801590,
    "POPULATION": 35834558,
    "GDP_USD_TRILLION": 0.022,
    "CAPITAL_EN": "Maputo",
    "CAPITAL_ZH": "马普托",
    "PINYIN_FULL": "mosangbike",
    "PINYIN_INITIAL": "msbk"
  },
  "MRT": {
    "NAME_EN": "Mauritania",
    "NAME_ZH": "毛里塔尼亚",
    "AREA_KM2": 1030700,
    "POPULATION": 4629041,
    "GDP_USD_TRILLION": 0.012,
    "CAPITAL_EN": "Nouakchott",
    "CAPITAL_ZH": "努瓦克肖特",
    "PINYIN_FULL": "maolitaniya",
    "PINYIN_INITIAL": "mltny"
  },
  "MWI": {
    "NAME_EN": "Malawi",
    "NAME_ZH": "马拉维",
    "AREA_KM2": 118484,
    "POPULATION": 24056975,
    "GDP_USD_TRILLION": 0.015,
    "CAPITAL_EN": "Lilongwe",
    "CAPITAL_ZH": "利隆圭",
    "PINYIN_FULL": "malawei",
    "PINYIN_INITIAL": "mlw"
  },
  "MYS": {
    "NAME_EN": "Malaysia",
    "NAME_ZH": "马来西亚",
    "AREA_KM2": 330803,
    "POPULATION": 33852033,
    "GDP_USD_TRILLION": 0.472,
    "CAPITAL_EN": "Kuala Lumpur",
    "CAPITAL_ZH": "吉隆坡",
    "PINYIN_FULL": "malaixiya",
    "PINYIN_INITIAL": "mlxy"
  },
  "NAM": {
    "NAME_EN": "Namibia",
    "NAME_ZH": "纳米比亚",
    "AREA_KM2": 825615,
    "POPULATION": 3049226,
    "GDP_USD_TRILLION": 0.015,
    "CAPITAL_EN": "Windhoek",
    "CAPITAL_ZH": "温得和克",
    "PINYIN_FULL": "namibiya",
    "PINYIN_INITIAL": "nmby"
  },
  "NCL": {
    "NAME_EN": "New Caledonia",
    "NAME_ZH": "新喀里多尼亚",
    "AREA_KM2": 18575,
    "POPULATION": 292639,
    "GDP_USD_TRILLION": 0.0085,
    "CAPITAL_EN": "Nouméa",
    "CAPITAL_ZH": "努美阿",
    "PINYIN_FULL": "xinkaliduoniya",
    "PINYIN_INITIAL": "xkldny"
  },
  "NER": {
    "NAME_EN": "Niger",
    "NAME_ZH": "尼日尔",
    "AREA_KM2": 1267000,
    "POPULATION": 29125520,
    "GDP_USD_TRILLION": 0.022,
    "CAPITAL_EN": "Niamey",
    "CAPITAL_ZH": "尼亚美",
    "PINYIN_FULL": "nirier",
    "PINYIN_INITIAL": "nre"
  },
  "NGA": {
    "NAME_EN": "Nigeria",
    "NAME_ZH": "尼日利亚",
    "AREA_KM2": 923768,
    "POPULATION": 237576970,
    "GDP_USD_TRILLION": 0.29,
    "CAPITAL_EN": "Abuja",
    "CAPITAL_ZH": "阿布贾",
    "PINYIN_FULL": "niriliya",
    "PINYIN_INITIAL": "nrly"
  },
  "NIC": {
    "NAME_EN": "Nicaragua",
    "NAME_ZH": "尼加拉瓜",
    "AREA_KM2": 130373,
    "POPULATION": 6664400,
    "GDP_USD_TRILLION": 0.022,
    "CAPITAL_EN": "Managua",
    "CAPITAL_ZH": "马那瓜",
    "PINYIN_FULL": "nijialagua",
    "PINYIN_INITIAL": "njlg"
  },
  "NLD": {
    "NAME_EN": "Netherlands",
    "NAME_ZH": "荷兰",
    "AREA_KM2": 41850,
    "POPULATION": 18044027,
    "GDP_USD_TRILLION": 1.33,
    "CAPITAL_EN": "Amsterdam",
    "CAPITAL_ZH": "阿姆斯特丹",
    "PINYIN_FULL": "helan",
    "PINYIN_INITIAL": "hl"
  },
  "NOR": {
    "NAME_EN": "Norway",
    "NAME_ZH": "挪威",
    "AREA_KM2": 323802,
    "POPULATION": 5618354,
    "GDP_USD_TRILLION": 0.531,
    "CAPITAL_EN": "Oslo",
    "CAPITAL_ZH": "奥斯陆",
    "PINYIN_FULL": "nuowei",
    "PINYIN_INITIAL": "nw"
  },
  "NPL": {
    "NAME_EN": "Nepal",
    "NAME_ZH": "尼泊尔",
    "AREA_KM2": 147181,
    "POPULATION": 29645181,
    "GDP_USD_TRILLION": 0.045,
    "CAPITAL_EN": "Kathmandu",
    "CAPITAL_ZH": "加德满都",
    "PINYIN_FULL": "niboer",
    "PINYIN_INITIAL": "nbe"
  },
  "NZL": {
    "NAME_EN": "New Zealand",
    "NAME_ZH": "新西兰",
    "AREA_KM2": 268838,
    "POPULATION": 5323500,
    "GDP_USD_TRILLION": 0.259,
    "CAPITAL_EN": "Wellington",
    "CAPITAL_ZH": "惠灵顿",
    "PINYIN_FULL": "xinxilan",
    "PINYIN_INITIAL": "xxl"
  },
  "OMN": {
    "NAME_EN": "Oman",
    "NAME_ZH": "阿曼",
    "AREA_KM2": 309500,
    "POPULATION": 5307411,
    "GDP_USD_TRILLION": 0.106,
    "CAPITAL_EN": "Muscat",
    "CAPITAL_ZH": "马斯喀特",
    "PINYIN_FULL": "aman",
    "PINYIN_INITIAL": "am"
  },
  "PAK": {
    "NAME_EN": "Pakistan",
    "NAME_ZH": "巴基斯坦",
    "AREA_KM2": 881913,
    "POPULATION": 240490000,
    "GDP_USD_TRILLION": 0.408,
    "CAPITAL_EN": "Islamabad",
    "CAPITAL_ZH": "伊斯兰堡",
    "PINYIN_FULL": "bajisitan",
    "PINYIN_INITIAL": "bjst"
  },
  "PAN": {
    "NAME_EN": "Panama",
    "NAME_ZH": "巴拿马",
    "AREA_KM2": 75417,
    "POPULATION": 4565559,
    "GDP_USD_TRILLION": 0.09,
    "CAPITAL_EN": "Panama City",
    "CAPITAL_ZH": "巴拿马城",
    "PINYIN_FULL": "banama",
    "PINYIN_INITIAL": "bnm"
  },
  "PER": {
    "NAME_EN": "Peru",
    "NAME_ZH": "秘鲁",
    "AREA_KM2": 1285216,
    "POPULATION": 34408962,
    "GDP_USD_TRILLION": 0.341,
    "CAPITAL_EN": "Lima",
    "CAPITAL_ZH": "利马",
    "PINYIN_FULL": "bilu",
    "PINYIN_INITIAL": "bl"
  },
  "PHL": {
    "NAME_EN": "Philippines",
    "NAME_ZH": "菲律宾",
    "AREA_KM2": 300000,
    "POPULATION": 114085672,
    "GDP_USD_TRILLION": 0.487,
    "CAPITAL_EN": "Manila",
    "CAPITAL_ZH": "马尼拉",
    "PINYIN_FULL": "feilübin",
    "PINYIN_INITIAL": "flb"
  },
  "PNG": {
    "NAME_EN": "Papua New Guinea",
    "NAME_ZH": "巴布亚新几内亚",
    "AREA_KM2": 462840,
    "POPULATION": 12802823,
    "GDP_USD_TRILLION": 0.032,
    "CAPITAL_EN": "Port Moresby",
    "CAPITAL_ZH": "莫尔兹比港",
    "PINYIN_FULL": "babuyaxinjineiya",
    "PINYIN_INITIAL": "bbyxjny"
  },
  "POL": {
    "NAME_EN": "Poland",
    "NAME_ZH": "波兰",
    "AREA_KM2": 312679,
    "POPULATION": 36497495,
    "GDP_USD_TRILLION": 1.04,
    "CAPITAL_EN": "Warsaw",
    "CAPITAL_ZH": "华沙",
    "PINYIN_FULL": "bolan",
    "PINYIN_INITIAL": "bl"
  },
  "PRI": {
    "NAME_EN": "Puerto Rico",
    "NAME_ZH": "波多黎各",
    "AREA_KM2": 9104,
    "POPULATION": 3175283,
    "GDP_USD_TRILLION": 0.127,
    "CAPITAL_EN": "San Juan",
    "CAPITAL_ZH": "圣胡安",
    "PINYIN_FULL": "boduolige",
    "PINYIN_INITIAL": "bdlg"
  },
  "PRK": {
    "NAME_EN": "North Korea",
    "NAME_ZH": "朝鲜",
    "AREA_KM2": 120538,
    "POPULATION": 26498823,
    "GDP_USD_TRILLION": 0.04,
    "CAPITAL_EN": "Pyongyang",
    "CAPITAL_ZH": "平壤",
    "PINYIN_FULL": "chaoxian",
    "PINYIN_INITIAL": "cx"
  },
  "PRT": {
    "NAME_EN": "Portugal",
    "NAME_ZH": "葡萄牙",
    "AREA_KM2": 92090,
    "POPULATION": 10769543,
    "GDP_USD_TRILLION": 0.346,
    "CAPITAL_EN": "Lisbon",
    "CAPITAL_ZH": "里斯本",
    "PINYIN_FULL": "putaoya",
    "PINYIN_INITIAL": "pty"
  },
  "PRY": {
    "NAME_EN": "Paraguay",
    "NAME_ZH": "巴拉圭",
    "AREA_KM2": 406752,
    "POPULATION": 6417076,
    "GDP_USD_TRILLION": 0.049,
    "CAPITAL_EN": "Asunción",
    "CAPITAL_ZH": "亚松森",
    "PINYIN_FULL": "balagui",
    "PINYIN_INITIAL": "blg"
  },
  "PSE": {
    "NAME_EN": "Palestine",
    "NAME_ZH": "巴勒斯坦",
    "AREA_KM2": 6220,
    "POPULATION": 5737179,
    "GDP_USD_TRILLION": 0.014,
    "CAPITAL_EN": "Ramallah",
    "CAPITAL_ZH": "拉马拉",
    "PINYIN_FULL": "balesitan",
    "PINYIN_INITIAL": "blst"
  },
  "QAT": {
    "NAME_EN": "Qatar",
    "NAME_ZH": "卡塔尔",
    "AREA_KM2": 11586,
    "POPULATION": 3174926,
    "GDP_USD_TRILLION": 0.221,
    "CAPITAL_EN": "Doha",
    "CAPITAL_ZH": "多哈",
    "PINYIN_FULL": "kataer",
    "PINYIN_INITIAL": "kte"
  },
  "ROU": {
    "NAME_EN": "Romania",
    "NAME_ZH": "罗马尼亚",
    "AREA_KM2": 238391,
    "POPULATION": 18831698,
    "GDP_USD_TRILLION": 0.428,
    "CAPITAL_EN": "Bucharest",
    "CAPITAL_ZH": "布加勒斯特",
    "PINYIN_FULL": "luomaniya",
    "PINYIN_INITIAL": "lmny"
  },
  "RUS": {
    "NAME_EN": "Russia",
    "NAME_ZH": "俄罗斯",
    "AREA_KM2": 17098246,
    "POPULATION": 143997393,
    "GDP_USD_TRILLION": 2.59,
    "CAPITAL_EN": "Moscow",
    "CAPITAL_ZH": "莫斯科",
    "PINYIN_FULL": "eluosi",
    "PINYIN_INITIAL": "els"
  },
  "RWA": {
    "NAME_EN": "Rwanda",
    "NAME_ZH": "卢旺达",
    "AREA_KM2": 26338,
    "POPULATION": 14162000,
    "GDP_USD_TRILLION": 0.016,
    "CAPITAL_EN": "Kigali",
    "CAPITAL_ZH": "基加利",
    "PINYIN_FULL": "luwangda",
    "PINYIN_INITIAL": "lwd"
  },
  "SAU": {
    "NAME_EN": "Saudi Arabia",
    "NAME_ZH": "沙特阿拉伯",
    "AREA_KM2": 2149690,
    "POPULATION": 36006286,
    "GDP_USD_TRILLION": 1.28,
    "CAPITAL_EN": "Riyadh",
    "CAPITAL_ZH": "利雅得",
    "PINYIN_FULL": "shatealabo",
    "PINYIN_INITIAL": "stalb"
  },
  "SDN": {
    "NAME_EN": "Sudan",
    "NAME_ZH": "苏丹",
    "AREA_KM2": 1886068,
    "POPULATION": 50418040,
    "GDP_USD_TRILLION": 0.04,
    "CAPITAL_EN": "Khartoum",
    "CAPITAL_ZH": "喀土穆",
    "PINYIN_FULL": "sudan",
    "PINYIN_INITIAL": "sd"
  },
  "SEN": {
    "NAME_EN": "Senegal",
    "NAME_ZH": "塞内加尔",
    "AREA_KM2": 196722,
    "POPULATION": 19173045,
    "GDP_USD_TRILLION": 0.037,
    "CAPITAL_EN": "Dakar",
    "CAPITAL_ZH": "达喀尔",
    "PINYIN_FULL": "saineijiaer",
    "PINYIN_INITIAL": "snje"
  },
  "SLB": {
    "NAME_EN": "Solomon Is.",
    "NAME_ZH": "所罗门群岛",
    "AREA_KM2": 28896,
    "POPULATION": 798079,
    "GDP_USD_TRILLION": 0.0017,
    "CAPITAL_EN": "Honiara",
    "CAPITAL_ZH": "霍尼亚拉",
    "PINYIN_FULL": "suoluomenqundao",
    "PINYIN_INITIAL": "slmqd"
  },
  "SLE": {
    "NAME_EN": "Sierra Leone",
    "NAME_ZH": "塞拉利昂",
    "AREA_KM2": 71740,
    "POPULATION": 8820082,
    "GDP_USD_TRILLION": 0.0077,
    "CAPITAL_EN": "Freetown",
    "CAPITAL_ZH": "弗里敦",
    "PINYIN_FULL": "sailaliang",
    "PINYIN_INITIAL": "slla"
  },
  "SLV": {
    "NAME_EN": "El Salvador",
    "NAME_ZH": "萨尔瓦多",
    "AREA_KM2": 21041,
    "POPULATION": 6382567,
    "GDP_USD_TRILLION": 0.037,
    "CAPITAL_EN": "San Salvador",
    "CAPITAL_ZH": "圣萨尔瓦多",
    "PINYIN_FULL": "saerwaduo",
    "PINYIN_INITIAL": "sewd"
  },
  "SOM": {
    "NAME_EN": "Somalia",
    "NAME_ZH": "索马里",
    "AREA_KM2": 637657,
    "POPULATION": 16962709,
    "GDP_USD_TRILLION": 0.013,
    "CAPITAL_EN": "Mogadishu",
    "CAPITAL_ZH": "摩加迪沙",
    "PINYIN_FULL": "suomali",
    "PINYIN_INITIAL": "sml"
  },
  "SRB": {
    "NAME_EN": "Serbia",
    "NAME_ZH": "塞尔维亚",
    "AREA_KM2": 88361,
    "POPULATION": 6539768,
    "GDP_USD_TRILLION": 0.1,
    "CAPITAL_EN": "Belgrade",
    "CAPITAL_ZH": "贝尔格莱德",
    "PINYIN_FULL": "saierweiya",
    "PINYIN_INITIAL": "sewy"
  },
  "SSD": {
    "NAME_EN": "S. Sudan",
    "NAME_ZH": "南苏丹",
    "AREA_KM2": 619745,
    "POPULATION": 12188788,
    "GDP_USD_TRILLION": 0.0057,
    "CAPITAL_EN": "Juba",
    "CAPITAL_ZH": "朱巴",
    "PINYIN_FULL": "nansudan",
    "PINYIN_INITIAL": "nsd"
  },
  "SUR": {
    "NAME_EN": "Suriname",
    "NAME_ZH": "苏里南",
    "AREA_KM2": 163820,
    "POPULATION": 657020,
    "GDP_USD_TRILLION": 0.0047,
    "CAPITAL_EN": "Paramaribo",
    "CAPITAL_ZH": "帕拉马里博",
    "PINYIN_FULL": "sulinan",
    "PINYIN_INITIAL": "sln"
  },
  "SVK": {
    "NAME_EN": "Slovakia",
    "NAME_ZH": "斯洛伐克",
    "AREA_KM2": 49035,
    "POPULATION": 5419451,
    "GDP_USD_TRILLION": 0.154,
    "CAPITAL_EN": "Bratislava",
    "CAPITAL_ZH": "布拉迪斯拉发",
    "PINYIN_FULL": "siluofake",
    "PINYIN_INITIAL": "slfk"
  },
  "SVN": {
    "NAME_EN": "Slovenia",
    "NAME_ZH": "斯洛文尼亚",
    "AREA_KM2": 20273,
    "POPULATION": 2130850,
    "GDP_USD_TRILLION": 0.08,
    "CAPITAL_EN": "Ljubljana",
    "CAPITAL_ZH": "卢布尔雅那",
    "PINYIN_FULL": "siluowenniya",
    "PINYIN_INITIAL": "slwny"
  },
  "SWE": {
    "NAME_EN": "Sweden",
    "NAME_ZH": "瑞典",
    "AREA_KM2": 450295,
    "POPULATION": 10676341,
    "GDP_USD_TRILLION": 0.669,
    "CAPITAL_EN": "Stockholm",
    "CAPITAL_ZH": "斯德哥尔摩",
    "PINYIN_FULL": "ruidian",
    "PINYIN_INITIAL": "rd"
  },
  "SWZ": {
    "NAME_EN": "Eswatini",
    "NAME_ZH": "斯威士兰",
    "AREA_KM2": 17364,
    "POPULATION": 1162925,
    "GDP_USD_TRILLION": 0.0052,
    "CAPITAL_EN": "Mbabane",
    "CAPITAL_ZH": "姆巴巴内",
    "PINYIN_FULL": "siweishilan",
    "PINYIN_INITIAL": "swsl"
  },
  "SYR": {
    "NAME_EN": "Syria",
    "NAME_ZH": "叙利亚",
    "AREA_KM2": 185180,
    "POPULATION": 24672760,
    "GDP_USD_TRILLION": 0.024,
    "CAPITAL_EN": "Damascus",
    "CAPITAL_ZH": "大马士革",
    "PINYIN_FULL": "xuliya",
    "PINYIN_INITIAL": "xly"
  },
  "TCD": {
    "NAME_EN": "Chad",
    "NAME_ZH": "乍得",
    "AREA_KM2": 1284000,
    "POPULATION": 18961000,
    "GDP_USD_TRILLION": 0.022,
    "CAPITAL_EN": "N'Djamena",
    "CAPITAL_ZH": "恩贾梅纳",
    "PINYIN_FULL": "zhade",
    "PINYIN_INITIAL": "zd"
  },
  "TGO": {
    "NAME_EN": "Togo",
    "NAME_ZH": "多哥",
    "AREA_KM2": 56785,
    "POPULATION": 9781181,
    "GDP_USD_TRILLION": 0.012,
    "CAPITAL_EN": "Lomé",
    "CAPITAL_ZH": "洛美",
    "PINYIN_FULL": "duoge",
    "PINYIN_INITIAL": "dg"
  },
  "THA": {
    "NAME_EN": "Thailand",
    "NAME_ZH": "泰国",
    "AREA_KM2": 513120,
    "POPULATION": 71619863,
    "GDP_USD_TRILLION": 0.577,
    "CAPITAL_EN": "Bangkok",
    "CAPITAL_ZH": "曼谷",
    "PINYIN_FULL": "taiguo",
    "PINYIN_INITIAL": "tg"
  },
  "TJK": {
    "NAME_EN": "Tajikistan",
    "NAME_ZH": "塔吉克斯坦",
    "AREA_KM2": 143100,
    "POPULATION": 10360358,
    "GDP_USD_TRILLION": 0.018,
    "CAPITAL_EN": "Dushanbe",
    "CAPITAL_ZH": "杜尚别",
    "PINYIN_FULL": "tajikesitan",
    "PINYIN_INITIAL": "tjkst"
  },
  "TKM": {
    "NAME_EN": "Turkmenistan",
    "NAME_ZH": "土库曼斯坦",
    "AREA_KM2": 488100,
    "POPULATION": 6680000,
    "GDP_USD_TRILLION": 0.077,
    "CAPITAL_EN": "Ashgabat",
    "CAPITAL_ZH": "阿什哈巴德",
    "PINYIN_FULL": "tukumansitan",
    "PINYIN_INITIAL": "tkmst"
  },
  "TLS": {
    "NAME_EN": "Timor-Leste",
    "NAME_ZH": "东帝汶",
    "AREA_KM2": 14874,
    "POPULATION": 1409551,
    "GDP_USD_TRILLION": 0.0021,
    "CAPITAL_EN": "Dili",
    "CAPITAL_ZH": "帝力",
    "PINYIN_FULL": "dongdiwen",
    "PINYIN_INITIAL": "ddw"
  },
  "TTO": {
    "NAME_EN": "Trinidad and Tobago",
    "NAME_ZH": "特立尼达和多巴哥",
    "AREA_KM2": 5131,
    "POPULATION": 1434916,
    "GDP_USD_TRILLION": 0.026,
    "CAPITAL_EN": "Port of Spain",
    "CAPITAL_ZH": "西班牙港",
    "PINYIN_FULL": "telinidaheduobage",
    "PINYIN_INITIAL": "tlndhdbg"
  },
  "TUN": {
    "NAME_EN": "Tunisia",
    "NAME_ZH": "突尼斯",
    "AREA_KM2": 163610,
    "POPULATION": 12348573,
    "GDP_USD_TRILLION": 0.058,
    "CAPITAL_EN": "Tunis",
    "CAPITAL_ZH": "突尼斯",
    "PINYIN_FULL": "tunisi",
    "PINYIN_INITIAL": "tns"
  },
  "TUR": {
    "NAME_EN": "Turkey",
    "NAME_ZH": "土耳其",
    "AREA_KM2": 783562,
    "POPULATION": 85825000,
    "GDP_USD_TRILLION": 1.6,
    "CAPITAL_EN": "Ankara",
    "CAPITAL_ZH": "安卡拉",
    "PINYIN_FULL": "tuerqi",
    "PINYIN_INITIAL": "teq"
  },
  "TWN": {
    "NAME_EN": "Taiwan",
    "NAME_ZH": "台湾",
    "AREA_KM2": 36193,
    "POPULATION": 23299132,
    "GDP_USD_TRILLION": 0.92,
    "CAPITAL_EN": "Taipei",
    "CAPITAL_ZH": "台北",
    "PINYIN_FULL": "taiwan",
    "PINYIN_INITIAL": "tw"
  },
  "TZA": {
    "NAME_EN": "Tanzania",
    "NAME_ZH": "坦桑尼亚",
    "AREA_KM2": 947303,
    "POPULATION": 67619195,
    "GDP_USD_TRILLION": 0.087,
    "CAPITAL_EN": "Dodoma",
    "CAPITAL_ZH": "多多马",
    "PINYIN_FULL": "tansangniya",
    "PINYIN_INITIAL": "tsny"
  },
  "UGA": {
    "NAME_EN": "Uganda",
    "NAME_ZH": "乌干达",
    "AREA_KM2": 241551,
    "POPULATION": 48021786,
    "GDP_USD_TRILLION": 0.066,
    "CAPITAL_EN": "Kampala",
    "CAPITAL_ZH": "坎帕拉",
    "PINYIN_FULL": "wuganda",
    "PINYIN_INITIAL": "wgd"
  },
  "UKR": {
    "NAME_EN": "Ukraine",
    "NAME_ZH": "乌克兰",
    "AREA_KM2": 603550,
    "POPULATION": 32761762,
    "GDP_USD_TRILLION": 0.213,
    "CAPITAL_EN": "Kyiv",
    "CAPITAL_ZH": "基辅",
    "PINYIN_FULL": "wukelan",
    "PINYIN_INITIAL": "wkl"
  },
  "URY": {
    "NAME_EN": "Uruguay",
    "NAME_ZH": "乌拉圭",
    "AREA_KM2": 176215,
    "POPULATION": 3485931,
    "GDP_USD_TRILLION": 0.086,
    "CAPITAL_EN": "Montevideo",
    "CAPITAL_ZH": "蒙得维的亚",
    "PINYIN_FULL": "wulagui",
    "PINYIN_INITIAL": "wlg"
  },
  "USA": {
    "NAME_EN": "United States",
    "NAME_ZH": "美国",
    "AREA_KM2": 9833520,
    "POPULATION": 341890000,
    "GDP_USD_TRILLION": 30.77,
    "CAPITAL_EN": "Washington, D.C.",
    "CAPITAL_ZH": "华盛顿",
    "PINYIN_FULL": "meiguo",
    "PINYIN_INITIAL": "mg"
  },
  "UZB": {
    "NAME_EN": "Uzbekistan",
    "NAME_ZH": "乌兹别克斯坦",
    "AREA_KM2": 447400,
    "POPULATION": 38236700,
    "GDP_USD_TRILLION": 0.147,
    "CAPITAL_EN": "Tashkent",
    "CAPITAL_ZH": "塔什干",
    "PINYIN_FULL": "wuzibiekesitan",
    "PINYIN_INITIAL": "wzbkst"
  },
  "VEN": {
    "NAME_EN": "Venezuela",
    "NAME_ZH": "委内瑞拉",
    "AREA_KM2": 912050,
    "POPULATION": 26673712,
    "GDP_USD_TRILLION": 0.1,
    "CAPITAL_EN": "Caracas",
    "CAPITAL_ZH": "加拉加斯",
    "PINYIN_FULL": "weineiruila",
    "PINYIN_INITIAL": "wnrl"
  },
  "VNM": {
    "NAME_EN": "Vietnam",
    "NAME_ZH": "越南",
    "AREA_KM2": 331212,
    "POPULATION": 102300000,
    "GDP_USD_TRILLION": 0.494,
    "CAPITAL_EN": "Hanoi",
    "CAPITAL_ZH": "河内",
    "PINYIN_FULL": "yuenan",
    "PINYIN_INITIAL": "yn"
  },
  "VUT": {
    "NAME_EN": "Vanuatu",
    "NAME_ZH": "瓦努阿图",
    "AREA_KM2": 12189,
    "POPULATION": 334335,
    "GDP_USD_TRILLION": 0.0013,
    "CAPITAL_EN": "Port Vila",
    "CAPITAL_ZH": "维拉港",
    "PINYIN_FULL": "wanuatu",
    "PINYIN_INITIAL": "wnat"
  },
  "XKX": {
    "NAME_EN": "Kosovo",
    "NAME_ZH": "科索沃",
    "AREA_KM2": 10908,
    "POPULATION": 1575553,
    "GDP_USD_TRILLION": 0.012,
    "CAPITAL_EN": "Pristina",
    "CAPITAL_ZH": "普里什蒂纳",
    "PINYIN_FULL": "kesuowo",
    "PINYIN_INITIAL": "ksw"
  },
  "YEM": {
    "NAME_EN": "Yemen",
    "NAME_ZH": "也门",
    "AREA_KM2": 527968,
    "POPULATION": 18810297,
    "GDP_USD_TRILLION": 0.0079,
    "CAPITAL_EN": "Sana'a",
    "CAPITAL_ZH": "萨那",
    "PINYIN_FULL": "yemen",
    "PINYIN_INITIAL": "ym"
  },
  "ZAF": {
    "NAME_EN": "South Africa",
    "NAME_ZH": "南非",
    "AREA_KM2": 1221037,
    "POPULATION": 63101000,
    "GDP_USD_TRILLION": 0.427,
    "CAPITAL_EN": "Pretoria",
    "CAPITAL_ZH": "比勒陀利亚",
    "PINYIN_FULL": "nanfei",
    "PINYIN_INITIAL": "nf"
  },
  "ZMB": {
    "NAME_EN": "Zambia",
    "NAME_ZH": "赞比亚",
    "AREA_KM2": 752618,
    "POPULATION": 21913874,
    "GDP_USD_TRILLION": 0.029,
    "CAPITAL_EN": "Lusaka",
    "CAPITAL_ZH": "卢萨卡",
    "PINYIN_FULL": "zanbiya",
    "PINYIN_INITIAL": "zby"
  },
  "ZWE": {
    "NAME_EN": "Zimbabwe",
    "NAME_ZH": "津巴布韦",
    "AREA_KM2": 390757,
    "POPULATION": 17359716,
    "GDP_USD_TRILLION": 0.053,
    "CAPITAL_EN": "Harare",
    "CAPITAL_ZH": "哈拉雷",
    "PINYIN_FULL": "jinbabuwei",
    "PINYIN_INITIAL": "jbbw"
  }
}
